version: "3"

services:
  bachmanity-server:
    build:
      context: ./bachmanity-server
      dockerfile: ./docker/Dockerfile
    image: lastpenguin/bachmanity-server
    working_dir: /app/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e production"
    volumes:
      - ./bachmanity-server:/app
    env_file:
      - .env
    ports:
      - 3000:3000

  bachmanity-client:
    image: node:13-alpine
    working_dir: /app/
    volumes:
      - ./bachmanity-client:/app/
    command: "npm start"
    ports:
      - 5000:3000

  pg:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./.db_data:/var/lib/postgresql/data
  # web:
  #   image: nginx
  #   volumes:
  #     - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/mime.types:/etc/nginx/mime.types:ro
  #   command: [nginx-debug, "-g", "daemon off;"]
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - bachmanity-server
  #     - bachmanity-client
